# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_max', models.IntegerField(default=50)),
                ('temps_restant', models.IntegerField(default=0)),
                ('interesses', models.IntegerField(default=0)),
                ('libre', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('machine', 'Machine à laver'), ('seche_linge', 'Sèche linge')], max_length=20)),
            ],
        ),
    ]
