# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.IntegerField(default=50)),
                ('heure_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('temps_restant', models.DurationField(blank=True)),
                ('interesses', models.IntegerField(default=0)),
                ('libre', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('machine', 'Machine à laver'), ('seche_linge', 'Sèche linge')], default='Machine à laver', max_length=20)),
            ],
        ),
    ]
