# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laverie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appareil',
            name='compteur_actif',
            field=models.BooleanField(default=False),
        ),
    ]
