# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laverie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appareil',
            name='heure_fin',
        ),
        migrations.RemoveField(
            model_name='appareil',
            name='interesses',
        ),
        migrations.RemoveField(
            model_name='appareil',
            name='libre',
        ),
        migrations.RemoveField(
            model_name='appareil',
            name='temps_restant',
        ),
        migrations.RemoveField(
            model_name='appareil',
            name='type',
        ),
    ]
