# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laverie', '0002_auto_20160512_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='appareil',
            name='heure_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appareil',
            name='interesses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appareil',
            name='libre',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appareil',
            name='temps_restant',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='appareil',
            name='type',
            field=models.CharField(choices=[('machine', 'Machine à laver'), ('seche_linge', 'Sèche linge')], default='Machine à laver', max_length=20),
        ),
    ]
