# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laverie', '0005_utilisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appareil',
            name='temps_restant',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
    ]
