# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laverie', '0006_auto_20160512_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appareil',
            name='type',
            field=models.CharField(choices=[(b'machine', b'Machine \xc3\xa0 laver'), (b'seche_linge', b'S\xc3\xa8che linge')], default=b'machine', max_length=20),
        ),
    ]
